
const C=window.CATALOG,grid=document.querySelector('#grid'),title=document.querySelector('#title'),count=document.querySelector('#count'),crumbs=document.querySelector('#crumbs'),back=document.querySelector('#back'),search=document.querySelector('#search'),suggest=document.querySelector('#suggest'),modal=document.querySelector('#product');
let path=[];
function firstImage(cat,p){let v=p.variants[0];return p.images[v]}
function allProducts(){let a=[];for(let [cn,c] of Object.entries(C))for(let [gn,g] of Object.entries(c.groups))for(let [pn,p] of Object.entries(g.products))a.push({cn,gn,pn,p,icon:c.icon});return a}
function card(name,img,sub,cb){let e=document.createElement('article');e.className='card';e.innerHTML=`<img src="${img}" alt="${name}"><div class="cardBody"><h3>${name}</h3><p>${sub}</p><div class="browse">Browse options →</div></div>`;e.onclick=cb;return e}
function renderHome(){path=[];back.hidden=true;crumbs.textContent='';title.textContent='All roofing categories';grid.innerHTML='';let total=allProducts().length;count.textContent=`${Object.keys(C).length} categories • ${total} product lines`;for(let [cn,c] of Object.entries(C)){let first=Object.values(c.groups)[0], p=Object.values(first.products)[0];let n=Object.values(c.groups).reduce((s,g)=>s+Object.keys(g.products).length,0);grid.append(card(cn,firstImage(cn,p),`${Object.keys(c.groups).length} ranges • ${n} product lines`,()=>renderCategory(cn)))}}
function renderCategory(cn){path=[cn];back.hidden=false;let c=C[cn];crumbs.textContent=`Shop / ${cn}`;title.textContent=cn;grid.innerHTML='';count.textContent=`${Object.keys(c.groups).length} ranges`;for(let [gn,g] of Object.entries(c.groups)){let p=Object.values(g.products)[0];grid.append(card(gn,firstImage(cn,p),`${Object.keys(g.products).length} individual product types`,()=>renderGroup(cn,gn)))}scrollMain()}
function renderGroup(cn,gn){path=[cn,gn];let g=C[cn].groups[gn];crumbs.textContent=`Shop / ${cn} / ${gn}`;title.textContent=gn;grid.innerHTML='';count.textContent=`${Object.keys(g.products).length} products`;for(let [pn,p] of Object.entries(g.products))grid.append(card(pn,firstImage(cn,p),`${p.variants.length} selectable options`,()=>openProduct(cn,gn,pn,p)));scrollMain()}
function openProduct(cn,gn,pn,p){document.querySelector('#pCat').textContent=`${cn} • ${gn}`;document.querySelector('#pName').textContent=pn;let vars=document.querySelector('#variants'),thumbs=document.querySelector('#thumbs');vars.innerHTML='';thumbs.innerHTML='';function choose(v){document.querySelector('#heroImg').src=p.images[v];document.querySelector('#heroImg').alt=`${pn} - ${v}`;document.querySelector('#selected').textContent=v;[...vars.children].forEach(x=>x.classList.toggle('active',x.dataset.v===v));[...thumbs.children].forEach(x=>x.classList.toggle('active',x.dataset.v===v))}
p.variants.forEach(v=>{let b=document.createElement('button');b.className='variant';b.dataset.v=v;b.textContent=v;b.onclick=()=>choose(v);vars.append(b);let im=document.createElement('img');im.className='thumb';im.dataset.v=v;im.src=p.images[v];im.alt=v;im.onclick=()=>choose(v);thumbs.append(im)});choose(p.variants[0]);modal.hidden=false}
function scrollMain(){document.querySelector('main').scrollIntoView({behavior:'smooth'})}
back.onclick=()=>path.length===2?renderCategory(path[0]):renderHome();document.querySelector('#close').onclick=()=>modal.hidden=true;modal.onclick=e=>{if(e.target===modal)modal.hidden=true};
function doSearch(){let q=search.value.trim().toLowerCase();suggest.innerHTML='';if(!q){renderHome();return}let hits=allProducts().filter(x=>(x.cn+' '+x.gn+' '+x.pn+' '+x.p.variants.join(' ')).toLowerCase().includes(q));path=[];back.hidden=false;crumbs.textContent='Shop / Search';title.textContent=`Results for “${search.value}”`;count.textContent=`${hits.length} matching products`;grid.innerHTML='';hits.forEach(x=>grid.append(card(x.pn,firstImage(x.cn,x.p),`${x.cn} • ${x.gn} • ${x.p.variants.length} options`,()=>openProduct(x.cn,x.gn,x.pn,x.p))));scrollMain()}
function suggestions(){let q=search.value.trim().toLowerCase();suggest.innerHTML='';if(q.length<2)return;let hits=allProducts().filter(x=>(x.cn+' '+x.gn+' '+x.pn+' '+x.p.variants.join(' ')).toLowerCase().includes(q)).slice(0,6);hits.forEach(x=>{let d=document.createElement('div');d.className='suggestion';d.innerHTML=`<b>${x.pn}</b><small>${x.cn} • ${x.gn}</small>`;d.onclick=()=>{suggest.innerHTML='';openProduct(x.cn,x.gn,x.pn,x.p)};suggest.append(d)})}
search.addEventListener('input',suggestions);search.addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});document.querySelector('#searchBtn').onclick=doSearch;renderHome();
